group_imports = "StdExternalCrate"
wrap_comments = true
imports_granularity = "Crate"
reorder_impl_items = false
spaces_around_ranges = false
binop_separator = "Back"
match_arm_blocks = false
trailing_semicolon = false
trailing_comma = "Vertical"
